import React from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Car, Hotel, MapPin, Accessibility as AccessibilityIcon, ShieldCheck, ExternalLink, Plane, Train, Users } from "lucide-react";
import { tours, fleet, hotels, gallery } from "../data/content";
import EnquiryForm from "../components/EnquiryForm";

export function Tours(){return <><PageHero eyebrow="TOURS & SIGHTSEEING" title="Discover Shirdi and nearby destinations." intro="Flexible day trips and pilgrimage routes with pickup and drop coordination. Enquire for a customized plan."/><section className="section"><div className="container route-grid">{tours.map((t,i)=><article className="route-card route-large" key={t.title}><div className="route-number">0{i+1}</div><span className="pill">{t.tag}</span><h3>{t.title}</h3><p>{t.places}</p><div className="route-meta"><span><Car/> Pickup & drop</span><span><Users/> Custom group</span></div><Link className="btn btn-outline" to="/contact">Enquire for fare <ArrowRight size={16}/></Link></article>)}</div></section><div className="container form-wrap"><EnquiryForm defaultType="Tour Package"/></div></>}

export function Cabs(){return <><PageHero eyebrow="CAB SERVICES" title="One-way & round-trip cabs across India." intro="Tell us your pickup, drop, date and vehicle preference. We check availability and share the fare on WhatsApp."/><section className="section"><div className="container feature-grid"><div className="mini-card"><ArrowRight/><h3>One-Way</h3><p>Pickup from your city and drop at your destination.</p></div><div className="mini-card"><Car/><h3>Round Trip</h3><p>Return journeys for families and groups.</p></div><div className="mini-card"><Plane/><h3>Airport</h3><p>Airport pickup and drop coordination.</p></div><div className="mini-card"><Train/><h3>Railway</h3><p>Station pickup and drop to your destination.</p></div><div className="mini-card"><MapPin/><h3>Shirdi Local</h3><p>Local travel and sightseeing enquiries.</p></div><div className="mini-card"><Users/><h3>Group Travel</h3><p>Tempo Traveller options for larger groups.</p></div></div></section><div className="container form-wrap"><EnquiryForm/></div></>}

export function Fleet(){return <><PageHero eyebrow="OUR FLEET" title="Clean, comfortable vehicles for every group." intro="Choose a sedan, SUV, family MPV or Tempo Traveller. Vehicle availability and final fare are confirmed through enquiry."/><section className="section"><div className="container fleet-page-grid">{fleet.map(v=><article className="fleet-card" key={v.name}><div className="vehicle-photo large"><img src={v.image} alt={v.name}/><span>{v.passengers} seats</span></div><div className="fleet-body"><span className="vehicle-type">{v.type}</span><h3>{v.name}</h3><p>{v.note}</p><div className="vehicle-tags"><span>AC</span><span>Comfortable</span><span>Enquiry</span></div><a className="btn btn-outline" href={`https://wa.me/917498510536?text=${encodeURIComponent("Hello Sai Darshan Tour & Travel, I want to enquire about "+v.name+". Please share availability and fare.")}`} target="_blank" rel="noreferrer">Enquire on WhatsApp <ArrowRight size={16}/></a></div></article>)}</div></section></>}

export function Hotels(){return <><PageHero eyebrow="HOTEL ASSISTANCE" title="Find a stay that fits your Shirdi trip." intro="Share your dates, guests and preferences. We can help coordinate suitable hotel options; availability is confirmed manually."/><section className="section"><div className="container hotel-grid">{hotels.map(h=><article className="hotel-card" key={h.name}><div className="hotel-photo"><Hotel/></div><div><span className="pill">Shirdi</span><h3>{h.name}</h3><p><MapPin size={15}/> {h.distance}</p><div className="feature-tags">{h.features.map(f=><span key={f}>{f}</span>)}</div><a className="btn btn-outline" href="https://wa.me/917498510536?text=Hello%20Sai%20Darshan%2C%20I%20need%20hotel%20assistance%20in%20Shirdi." target="_blank" rel="noreferrer">Ask Availability</a></div></article>)}</div></section><div className="container form-wrap"><EnquiryForm defaultType="Hotel Assistance"/></div></>}

export function Darshan(){return <><PageHero eyebrow="DARSHAN ASSISTANCE" title="Plan your Shirdi Darshan with clear guidance." intro="We can help you understand the official booking process and coordinate your travel plan around your visit."/><section className="section"><div className="container info-grid"><div className="info-card"><ShieldCheck/><h3>Use official channels</h3><p>For Sansthan Darshan, Aarti and accommodation bookings, use the official Shri Saibaba Sansthan Trust channels.</p><a className="btn btn-primary" href="https://online.sai.org.in/" target="_blank" rel="noreferrer">Official Booking Portal <ExternalLink size={16}/></a></div><div className="info-card"><Car/><h3>We handle the travel side</h3><p>We can coordinate pickup, hotel assistance, local sightseeing and your return journey around your planned visit.</p><Link className="btn btn-outline" to="/cabs">Plan Transport</Link></div></div></section><div className="container disclaimer"><b>Important:</b> Sai Darshan Tour & Travel is an independent travel service provider and should not be presented as an official representative of Shri Saibaba Sansthan Trust unless verified authorization exists.</div><div className="container form-wrap"><EnquiryForm defaultType="Darshan Assistance"/></div></>}

export function Accessibility(){return <><PageHero eyebrow="ACCESSIBILITY" title="Travel assistance for seniors and people with mobility needs." intro="Request wheelchair or mobility assistance while planning your journey. Requirements are coordinated through enquiry."/><section className="section"><div className="container feature-grid"><div className="mini-card"><AccessibilityIcon/><h3>Wheelchair Request</h3><p>Tell us where and when assistance is needed.</p></div><div className="mini-card"><ShieldCheck/><h3>Senior Citizens</h3><p>Plan comfortable pickup, hotel and local transport.</p></div><div className="mini-card"><Car/><h3>Accessible Travel</h3><p>Share your specific mobility requirements in advance.</p></div></div></section><div className="container form-wrap"><EnquiryForm defaultType="Wheelchair Assistance"/></div></>}

export function Gallery(){return <><PageHero eyebrow="FLEET GALLERY" title="A closer look at our vehicle options." intro="Vehicle images below are model references. Replace them with the business's own vehicle photographs before production launch."/><section className="section"><div className="container gallery-grid fleet-gallery">{fleet.map(v=><figure key={v.name}><img src={v.image} alt={v.name}/><figcaption><b>{v.name}</b><span>{v.passengers} seats • {v.type}</span></figcaption></figure>)}</div></section></>}

export function Contact(){return <><PageHero eyebrow="CONTACT" title="Let's plan your journey." intro="Send your route and requirements. We will respond with availability and a quotation."/><div className="container contact-layout"><EnquiryForm/><div className="contact-side"><div className="contact-box"><MapPin/><h3>Shirdi, Maharashtra</h3><p>Local and all-India travel enquiries.</p><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Shirdi%2C%20Maharashtra" target="_blank" rel="noreferrer">Open Google Maps <ArrowRight size={15}/></a></div><div className="contact-box"><Car/><h3>One-way & round trips</h3><p>Pickup and drop coordination across India.</p></div><div className="contact-box"><Hotel/><h3>Hotel assistance</h3><p>Stay options can be coordinated on request.</p></div></div></div></>}

function PageHero({eyebrow,title,intro}){return <section className="page-hero"><div className="container"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{intro}</p></div></section>}
